### ISSUE TITLE
BirthDate View does not seem to work

### ISSUE THREAD

**Issue by cryptoman04** [AptoPayments/apto-ui-sdk-ios#2]
I've integrated the apto ui sdk, however when I attempt to get past the Birthdate form, I get an error saying the birthdate is not correct. Any way to get past this? Thanks

![image](https://user-images.githubusercontent.com/48849159/91954716-308b2700-ecd0-11ea-8f13-6a26178070f5.png)

**Comment by georgedotsmith** [comment]
Apologies for the delay. Had you previously created a user with that phone number? If you could also share the environment you were testing it, the phone number you used, the date of birth that you think should be working, and a timestamp of the event (if you have it) we can explore on our end.

**Comment by XaviLedge** [comment]
Hi, we are able to see a verification for a phone number ending in 577 on 09/02/2020. The birthdate sent to the server is 09/12/1991, while the users (we have 2 on different projects in SBX: Blegg and Outlet Finance) have different birthdates stored in the system.

**Comment by mulp** [comment]
Close it.
