### ISSUE TITLE
Getting errors when building for ARM64, also getting issues when attempting to build in general

### ISSUE THREAD

**Issue by srikanthsrnvs** [AptoPayments/apto-ui-sdk-ios#4]
![Screen Shot 2021-04-09 at 4 41 23 PM](https://user-images.githubusercontent.com/25404406/114238354-78eb8100-9952-11eb-96bc-553bd89afbf6.png)

Cannot seem to compile the SDK, and unsure what the problem is in general

**Comment by srikanthsrnvs** [comment]
The weird thing is that it works if you downgrade the version from 2.10.0 to 2.9.0 in your podfile

**Comment by mulp** [comment]
Hey @srikanthsrnvs,

thanks for reporting an issue. Could you please provide us with more information? 

Xcode version?
Xcode code commands tools?
Swift version?
Can you reproduce it in a sample project? If yes, could you please share it?

Cheers.

**Comment by srikanthsrnvs** [comment]
Closing this issue, in order to build, you have to set the pods project to `build active architecture only - yes`
